### ISSUE TITLE
동적 html 추가(Firebase + map함수)

### ISSUE THREAD

**Issue by shinb-bong** [btl831/moum#16]
코드는 word_Ranking

Firebase에서 불러온다음
![image](https://user-images.githubusercontent.com/81786969/163346263-34f9a6c8-8030-4d1d-998a-ae3f6283e9f0.png)
item에 넣고 map을 돌려서 차트로 만들려고 하는데 Objects are not valid as a React child 오류가 계속뜸

console.log랑 다 확인하는데도 왜그런질 모르겠음 

근데 이게 채팅방 구현도 결국 채팅 데이터베이스가 등록이 되면 그걸 받아와서 들어있는 데이터만큼 반복문을 통한 동적으로 채팅방에 만들어줘야하는데  아래 이슈 적어놓은것 처럼 개 쌩 html로 가거나  동일 오류가 사용됨

해결해주고 정답좀...

**Comment by shinb-bong** [comment]
![image](https://user-images.githubusercontent.com/81786969/163346933-76e16be4-0c6e-4cb6-8c0b-1595235748b8.png)


오류 사진 채팅방도 같은오류

**Comment by mohag123** [comment]
![image](https://user-images.githubusercontent.com/89440483/163374556-5f779a99-8476-482a-8d22-768da4da6090.png)
해결완료.
오류는 Objects are not valid as a React child / 오브젝트를 직접 jsx 코드 안에 사용할 때 발생하는 것.
원인은 "Date" 컴포넌트를 사용하여 만들어진 오브젝트를 호출해서 사용했기때문.
Date 컴포넌트로 만들어진 멤버는 number가 아니라 Object이다.



![1](https://user-images.githubusercontent.com/89440483/163378151-bf9ea138-abd4-4902-ad06-42f455b0c4bc.PNG)
[수정 이전의 코드]
![2](https://user-images.githubusercontent.com/89440483/163378176-b52abdcf-09f7-4346-871d-73c24e8d2ef4.PNG)
[수정 이후의 코드]

**Comment by mohag123** [comment]
추가로, 아래 firestore 사용량 이슈탭에도 한번 더 썼지만, 해당 페이지는 특히나 반복 읽기가 심각했었음.
한번 페이지가 렌더링 될 때 수백번 읽기를 하는 것을 확인함.
원인을 찾는게 좋을 것 같다.

**Comment by shinb-bong** [comment]
해당 페이지면 wordle_ranking ? 아니면 맨아래 이슈에 해당하는 페이지?

**Comment by mohag123** [comment]
Wordle Ranking

**Comment by shinb-bong** [comment]
okay 확인해봄 그리고 하나 아래 이슈사안에 적어논것도 한번 생각해주셈
왼쪽에서 클릭된 채팅방 id 불러오는 방법

**Comment by shinb-bong** [comment]
![image](https://user-images.githubusercontent.com/81786969/163383638-c2f601e3-4de3-41c5-a867-54e0dd69a247.png)

해결완료

**Comment by shinb-bong** [comment]
![image](https://user-images.githubusercontent.com/81786969/163383684-67a2a5d2-e090-4aa2-8db3-94ad6292e80c.png)

**Comment by shinb-bong** [comment]
![image](https://user-images.githubusercontent.com/81786969/163384458-5bcfd205-b299-4423-a42c-973b67cab4f5.png)
![image](https://user-images.githubusercontent.com/81786969/163384498-ab7ff633-53b7-4e5d-8116-f9e805e783ed.png)

두번째 파라미터를 넣어 해당 값이 갱신될때만 useEffect가 작동하게 냅둠
