### ISSUE TITLE
naver -login axios

### ISSUE THREAD

**Issue by shinb-bong** [btl831/moum#18]
보이는 것처럼 로그인이 성공적으로 구현이 되어 토큰발급과 localstorage에도 토큰 내용이 담겨졌다.
하지만 axios로 https://openapi.naver.com/v1/nid/me 에 토큰을 전달하여 유저정보를 받아서 다른 로그인 형식과 같이 localstorage에 넣고 firestore에도 넣어주려고 하는데 해당 단계에서 어려움이 생겨서 issue 올린다.

사진 첨부
<img width="1435" alt="스크린샷 2022-04-16 오후 7 19 44" src="https://user-images.githubusercontent.com/81786969/163671321-0d2cddd6-791e-42ea-bc76-f3820800065a.png">
:

**Comment by mohag123** [comment]
![1](https://user-images.githubusercontent.com/89440483/165337367-250a326e-f0ea-472c-b0af-99b05f158f0a.PNG)

![2](https://user-images.githubusercontent.com/89440483/165337406-10d118b5-3287-4c33-894d-620355dc19c2.PNG)

네이버 개발자 API를 참고하여 로그인을 구현해보기는 했다.
아직 약간은 어색한 부분이 있기도하고, 로그인 파트를 건들여보면서 기능을 추가해야할 부분도 보였다.
로그인 부분에 관해서는 앞으로 더 수정할 부분이 남았다고 생각.

네이버 자체에서 제공하는 예제에서 Node.js는 토큰 발행과 로그인 요청을 동시에 처리할 수 있다는 것에서 착안하여
NaverLogin 컴포넌트 하나 안에서 모두 구현하였으며, 이에 따라 server 폴더와 Server.js 파일은 삭제되었다.






+++++

추가로, 아니나다를까 CORS Policy 문제로 인한 오류가 발생했었다.
자료를 찾아보니, 우선은 Proxy 통해 간단하게 CORS를 피해갈 수는 있었지만,
추후에 서버를 배포하는 경우에는 이 부분에 대해서 조금 더 처리해 줄 필요가 있다고 한다.
아래는 그와 관련된 내용이 담긴 글이다.

< CORS 해결 -1 >
https://msyu1207.tistory.com/entry/React%EB%A1%9C-%EC%98%81%ED%99%94-%EC%A0%95%EB%B3%B4%EB%A5%BC-%EA%B2%80%EC%83%89%ED%95%B4%EB%B3%B4%EC%9E%90-%EB%91%90%EB%B2%88%EC%A7%B8-%EB%84%A4%EC%9D%B4%EB%B2%84-API-%EC%82%AC%EC%9A%A9-CORS-%EC%84%A4%EC%A0%95-%ED%95%98%EA%B8%B0?category=906762

< CORS 해결 -2 >
https://msyu1207.tistory.com/entry/React%EB%A1%9C-%EC%98%81%ED%99%94-%EA%B2%80%EC%83%89-%EC%82%AC%EC%9D%B4%ED%8A%B8%EB%A5%BC-%EB%A7%8C%EB%93%A4%EC%96%B4%EB%B3%B4%EC%9E%90-%EC%84%B8%EB%B2%88%EC%A7%B8-%EB%84%A4%EC%9D%B4%EB%B2%84-API-%EC%82%AC%EC%9A%A9-React-%EB%B0%B0%ED%8F%AC-CORS-%EC%84%A4%EC%A0%95-%ED%95%98%EA%B8%B0?category=906762

**Comment by shinb-bong** [comment]
오오 참고자료 다읽어보았고 확인했습니당
nginx 쓸때도 참고하면 괜찮을듯
