### ISSUE TITLE
Firestore 일일 사용량 제한 문제?

### ISSUE THREAD

**Issue by mohag123** [btl831/moum#8]
리액트 페이지에서 어느 정도 사용되면 firestore에 제한이 걸리는지는 모르겠지만,
ListPage와 Detail에서 db를 사용하는 부분에서 얼마 테스트해보지도 않았는데 제한이 걸리는 현상 발생
혹시나 useEffect hook 사용에서 매 렌더링마다 db를 가져오도록 코딩해서 그런가싶어서 그것도 일단 수정은 해둠
![firestore](https://user-images.githubusercontent.com/89440483/160288326-503c4482-9dd3-4422-9076-b1ae06daa17d.png)
.

**Comment by mohag123** [comment]
firestore가 원래 그런건지, 아니라면 원인을 찾으면 좋을듯?

**Comment by shinb-bong** [comment]
F12눌러보면  detail창에서 무한으로 console.log가 찍히고 있는거 보니깐 while문처럼 뭔가 계속불러와서 제한량이 넘은거 같은데 한정적 데이터 부르기라 개발자 도구 확인해보면서 개발해야할듯..

토요일에 확인해서 혹시 해결방법 있는지 한번 더 찾아볼께 
나도 그 이슈에서 커밋해서 그 이슈가 발생한 상태로 켜서 그런듯

결론: 현재 Detail 페이지가 useEffect에서 무한 불러오기중이니 개발자도구 확인하면서 개발해야함

**Comment by mohag123** [comment]
추가적으로 실험해본 결과 F12 개발자 창에서 콘솔에 오류가 안 찍히더라도 한번 새로고침(페이지 새로 렌더링) 할때마다
firestore 읽기 사용량이 50~100정도가 한꺼번에 증가하는 현상 확인....

**Comment by shinb-bong** [comment]
https://github.com/btl831/moum/issues/16#issuecomment-1099103136

여기에 적어놔서 파라미터를 추가로 적어 재랜더링 방지하여 Wordle_Ranking은 해결했고 다른 곳도 같은 에러 보이면 해결하겠음
